/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.latihan.scala.app

import com.latihan.scala.utilities.StringUtils

import org.apache.commons.text.WordUtils

object App {
   def main(args: Array[String]): Unit = {
        val tokens = StringUtils.split(MessageUtils.getMessage())
        val result = StringUtils.join(tokens)
        println(WordUtils.capitalize(result))
    }
}
